version: '3'

vars:
  ZMK_HOME: ./firmware
  BOARD: sparkfun_pro_micro_rp2040
  SHIELD_LEFT: terminus_est_left
  SHIELD_RIGHT: terminus_est_right

tasks:
  firmware:setup:
    desc: Setup ZMK development environment
    dir: '{{.ZMK_HOME}}'
    cmds:
      - echo "Setting up ZMK development environment..."
      - west init -l config
      - west update
      - west zephyr-export
      - echo "ZMK setup complete!"

  firmware:compile:
    desc: Compile the ZMK firmware for Terminus Est
    dir: '{{.ZMK_HOME}}'
    cmds:
      - west build -s zmk/app -d build/left -b {{.BOARD}} -- -DSHIELD={{.SHIELD_LEFT}} -DZMK_CONFIG="{{.ZMK_HOME}}/config"
      - west build -s zmk/app -d build/right -b {{.BOARD}} -- -DSHIELD={{.SHIELD_RIGHT}} -DZMK_CONFIG="{{.ZMK_HOME}}/config"

  firmware:test:
    desc: Test the firmware configuration without flashing
    dir: '{{.ZMK_HOME}}'
    cmds:
      - west build -s zmk/app -d build/left -b {{.BOARD}} --pristine -- -DSHIELD={{.SHIELD_LEFT}} -DZMK_CONFIG="{{.ZMK_HOME}}/config"
      - west build -s zmk/app -d build/right -b {{.BOARD}} --pristine -- -DSHIELD={{.SHIELD_RIGHT}} -DZMK_CONFIG="{{.ZMK_HOME}}/config"

  firmware:clean:
    desc: Clean build artifacts
    dir: '{{.ZMK_HOME}}'
    cmds:
      - rm -rf build/
      - rm -f *.uf2

  firmware:info:
    desc: Show keyboard information
    dir: '{{.ZMK_HOME}}'
    cmds:
      - echo "ZMK Terminus Est Configuration"
      - echo "Left shield {{.SHIELD_LEFT}}"
      - echo "Right shield {{.SHIELD_RIGHT}}"
      - echo "Board {{.BOARD}}"
