# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  ZMK_HOME: ./firmware
  BOARD: sparkfun_pro_micro_rp2040
  SHIELD: terminus_est

tasks:
  firmware:setup:
    desc: Setup ZMK development environment
    dir: '{{.ZMK_HOME}}'
    cmds:
      - echo "Setting up ZMK development environment..."
      - test -d .west || west init -l config
      - west update
      - west zephyr-export
      - echo "ZMK setup complete!"

  firmware:compile:
    desc: Compile the ZMK firmware for Terminus Est
    dir: '{{.ZMK_HOME}}'
    cmds:
      - west build -s zmk/app -d build -b {{.BOARD}} -- -DSHIELD={{.SHIELD}} -DZMK_CONFIG="/Users/rshnbhatia/github/personal/roshbhatia/terminus-est/firmware/config"

  firmware:test:
    desc: Test the firmware configuration without flashing
    dir: '{{.ZMK_HOME}}'
    cmds:
      - west build -s zmk/app -d build -b {{.BOARD}} --pristine -- -DSHIELD={{.SHIELD}} -DZMK_CONFIG="/Users/rshnbhatia/github/personal/roshbhatia/terminus-est/firmware/config"

  firmware:clean:
    desc: Clean build artifacts
    dir: '{{.ZMK_HOME}}'
    cmds:
      - rm -rf build/
      - rm -f *.uf2

  firmware:info:
    desc: Show keyboard information
    dir: '{{.ZMK_HOME}}'
    cmds:
      - echo "ZMK Terminus Est Configuration"
      - echo "Shield {{.SHIELD}}"
      - echo "Board {{.BOARD}}"
