# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  compile:
    desc: Compile terminus-est firmware
    cmds:
      - qmk compile

  flash:
    desc: Flash terminus-est firmware
    cmds:
      - qmk flash

