#!/usr/bin/env python3
"""
KLE JSON to OpenSCAD switch positions converter
Parses keyboard-layout.json and generates OpenSCAD array of switch positions
"""

import json
import sys
import os
import re

def parse_kle_json(layout_data):
    """
    Parse KLE JSON format and return list of switch positions.
    Returns: [(x, y, width), ...]
    """
    switches = []
    current_y = 0

    for row in layout_data:
        current_x = 0
        current_width = 1  # Default key width in units

        for item in row:
            if isinstance(item, dict):
                # This is a metadata object that modifies the next key
                if 'x' in item:
                    current_x += item['x']
                if 'y' in item:
                    current_y += item['y']
                if 'w' in item:
                    current_width = item['w']
                # Ignore other properties like 'a' (alignment), etc.

            elif isinstance(item, str):
                # This is an actual key
                switches.append((current_x, current_y, current_width))
                # Move to next position
                current_x += current_width
                # Reset width to default for next key
                current_width = 1

        # Move to next row
        current_y += 1

    return switches

def generate_openscad_array(switches):
    """
    Generate OpenSCAD array declaration from switch positions.
    """
    lines = ["switch_positions = ["]

    # Group by row for readability
    current_row = 0
    row_switches = []

    for x, y, w in switches:
        if y != current_row:
            # Output previous row
            if row_switches:
                lines.append(f"    // Row {current_row}")
                lines.append("    " + ", ".join(row_switches) + ",")
                lines.append("")
            row_switches = []
            current_row = y

        row_switches.append(f"[{x}, {y}, {w}]")

    # Output last row
    if row_switches:
        lines.append(f"    // Row {current_row}")
        lines.append("    " + ", ".join(row_switches))

    lines.append("];")
    return "\n".join(lines)

def update_plate_file(switches, plate_file):
    """
    Update the plate.scad file with new switch positions.
    """
    # Generate the switch positions array
    openscad_code = generate_openscad_array(switches)

    # Calculate stats
    min_x = min(s[0] for s in switches)
    max_x = max(s[0] for s in switches)
    min_y = min(s[1] for s in switches)
    max_y = max(s[1] for s in switches)

    # Add comments with metadata
    full_code = f"""// Generated by kle-to-openscad.py from keyboard-layout.json
// Total switches: {len(switches)}
// Dimensions: {max_x - min_x + 1}U x {max_y - min_y + 1}U
{openscad_code}"""

    # Read the current plate file
    with open(plate_file, 'r') as f:
        content = f.read()

    # Replace the switch_positions array (find the pattern between comments and the array)
    pattern = r'// Generated by kle-to-openscad\.py.*?switch_positions = \[.*?\];'
    replacement = full_code

    new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

    # Write back to file
    with open(plate_file, 'w') as f:
        f.write(new_content)

    return len(switches), max_x - min_x + 1, max_y - min_y + 1

def main():
    # Determine paths based on script location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(script_dir, '../..'))

    # Paths
    json_file = os.path.join(repo_root, 'layout/keyboard-layout.json')
    plate_file = os.path.join(repo_root, 'plate/v2/plate.scad')

    print(f"Loading {json_file}...")
    with open(json_file, 'r') as f:
        layout = json.load(f)

    # Parse the layout
    switches = parse_kle_json(layout)

    # Update the plate file
    print(f"Found {len(switches)} switches")
    num_switches, width_u, height_u = update_plate_file(switches, plate_file)

    print(f"✓ Updated {plate_file}")
    print(f"  {num_switches} switches, {width_u}U × {height_u}U")

if __name__ == "__main__":
    main()
