# This file generates the GitHub Actions matrix
# For simple single-board keyboards, remove the matrix entries for other boards
include:
  - board: nice_nano_v2
    shield: terminus_est_left
  - board: nice_nano_v2
    shield: terminus_est_right